publish_mode: editorial_workflow
backend:
  name: git-gateway
  branch: main
collections:
  - name: FAQ
    label: FAQ
    folder: modules/faqs/
    create: true
    slug: "{{order}}-{{day}}-{{month}}-{{year}}-{{category}}-{{title}}"
    fields:
      - name: category
        label: Category
        widget: "select"
        options:
          - { label: "Starting Out", value: "Starting Out" }
          - { label: "Building", value: "Building" }
          - { label: "Betaflight", value: "Betaflight" }
          - { label: "Video", value: "Video" }
          - { label: "Radio", value: "Radio" }
          - { label: "Hardware", value: "Hardware" }
      - { label: "Order", name: "order", widget: "number" }
      - { label: "Question", name: "title", widget: "text" }
      - { label: "ID", name: "id", widget: "text" }
      - { label: "Answer", name: "answer", widget: "markdown" }

  - name: 5" Beginner Build
    label: 5" Beginner Build
    folder: modules/buildLists/5inch-beginner/
    create: true
    slug: "{{order}}-{{day}}-{{month}}-{{year}}-{{category}}-{{title}}"
    sortable_fields: [order, title, category, color]
    view_groups: 
      - label: Category
        field: category
      - label: Price Range
        field: color
    view_filters: 
      - label: Frames
        field: category
        pattern: "Frames"
      - label: Motors
        field: category
        pattern: "Motors"
      - label: Flight Controllers
        field: category
        pattern: "Flight Controllers"
      - label: ESCs
        field: category
        pattern: "ESCs"
      - label: Video Transmitters
        field: category
        pattern: "Video Transmitters"
    fields:
      - label: Category
        name: category
        widget: "select"
        options:
          - { label: "Frames", value: "Frames" }
          - { label: "Motors", value: "Motors" }
          - { label: "Flight Controllers", value: "Flight Controllers" }
          - { label: "ESCs", value: "ESCs" }
          - { label: "Video Transmitters", value: "Video Transmitters" }
      - label: Price Range
        name: color
        widget: "select"
        options:
          - { label: "Budget", value: "green" }
          - { label: "Mid-Range", value: "orange" }
          - { label: "High-end", value: "red" }
          - { label: "Varied", value: "violet" }
      - {label: "Visible", name: "visible", widget: "boolean", default: true}
      - { label: "Order", name: "order", widget: "number" }
      - { label: "Title", name: "title", widget: "text" }
      - { label: "Link", name: "link", widget: "text" }
      - { label: "Image", name: "img", widget: "image"}
      - { label: "Description", name: "text", widget: "text" }

      - { label: "Price", name: "price", widget: "text" }
      - { label: "Point 1", name: "point1", widget: "text", required: false }
      - { label: "Point 2", name: "point2", widget: "text", required: false }
      - { label: "Point 3", name: "point3", widget: "text", required: false }
      - { label: "Point 4", name: "point4", widget: "text", required: false }
      - { label: "Point 5", name: "point5", widget: "text", required: false }

  - name: 5" Race Build
    label: 5" Race Build
    identifier_field: title
    folder: modules/buildLists/5inch-race/
    create: true
    slug: "{{order}}-{{day}}-{{month}}-{{year}}-{{category}}-{{title}}"
    sortable_fields: [order, title, category, color]
    view_groups: 
      - label: Category
        field: category
      - label: Price Range
        field: color
    view_filters: 
      - label: Frames
        field: category
        pattern: "Frames"
      - label: Motors
        field: category
        pattern: "Motors"
      - label: Flight Controllers
        field: category
        pattern: "Flight Controllers"
      - label: ESCs
        field: category
        pattern: "ESCs"
      - label: Video Transmitters
        field: category
        pattern: "Video Transmitters"
    fields:
      - label: Category
        name: category
        widget: "select"
        options:
          - { label: "Frames", value: "Frames" }
          - { label: "Motors", value: "Motors" }
          - { label: "Flight Controllers", value: "Flight Controllers" }
          - { label: "ESCs", value: "ESCs" }
          - { label: "Video Transmitters", value: "Video Transmitters" }
          - { label: "Recommended Builds", value: "Recommended Builds" }

      - { label: "Group", name: "group", widget: "text", required: false }
      - label: Price Range
        name: color
        widget: "select"
        options:
          - { label: "Budget", value: "green" }
          - { label: "Mid-Range", value: "orange" }
          - { label: "High-end", value: "red" }
          - { label: "Varied", value: "violet" }

      - { label: "Visible", name: "visible", widget: "boolean", default: true}
      - { label: "Order", name: "order", widget: "number" }
      - { label: "Title", name: "title", widget: "text" }
      - { label: "Link", name: "link", widget: "text" }
      - { label: "Image", name: "img", widget: "image"}
      - { label: "Description", name: "text", widget: "text" }

      - { label: "Recommended", name: "recommended", widget: "relation", collection: '5" Race Build', searchFields: ["title"], valueField: "title", displayFields: ["title"], multiple: true, required: false}

      - { label: "Price", name: "price", widget: "string" }
      - { label: "Point 1", name: "point1", widget: "string", required: false }
      - { label: "Point 2", name: "point2", widget: "string", required: false }
      - { label: "Point 3", name: "point3", widget: "string", required: false }
      - { label: "Point 4", name: "point4", widget: "string", required: false }
      - { label: "Point 5", name: "point5", widget: "string", required: false }


  - name: 5inch-advanced
    label: 5" Advanced Build
    identifier_field: title
    folder: modules/buildLists/5inch-advanced/
    create: true
    slug: "{{order}}-{{day}}-{{month}}-{{year}}-{{category}}-{{title}}"
    sortable_fields: [order, title, category, color]
    view_groups: 
      - label: Category
        field: category
      - label: Price Range
        field: color
    view_filters: 
      - label: Frames
        field: category
        pattern: "Frames"
      - label: Motors
        field: category
        pattern: "Motors"
      - label: Flight Controllers
        field: category
        pattern: "Flight Controllers"
      - label: ESCs
        field: category
        pattern: "ESCs"
      - label: Video Transmitters
        field: category
        pattern: "Video Transmitters"
    fields:
      - label: Category
        name: category
        widget: "select"
        options:
          - { label: "Frames", value: "Frames" }
          - { label: "Motors", value: "Motors" }
          - { label: "Flight Controllers", value: "Flight Controllers" }
          - { label: "ESCs", value: "ESCs" }
          - { label: "Video Transmitters", value: "Video Transmitters" }
          - { label: "Recommended Builds", value: "Recommended Builds" }

      - { label: "Group", name: "group", widget: "text", required: false }
      - label: Price Range
        name: color
        widget: "select"
        options:
          - { label: "Budget", value: "green" }
          - { label: "Mid-Range", value: "orange" }
          - { label: "High-end", value: "red" }
          - { label: "Varied", value: "violet" }

      - { label: "Visible", name: "visible", widget: "boolean", default: true}
      - { label: "Order", name: "order", widget: "number" }
      - { label: "Title", name: "title", widget: "text" }
      - { label: "Link", name: "link", widget: "text" }
      - { label: "Image", name: "img", widget: "image"}
      - { label: "Description", name: "text", widget: "text" }

      - { label: "Recommended", name: "recommended", widget: "relation", collection: '5" Advanced Build', searchFields: ["title"], valueField: "title", displayFields: ["title"], multiple: true, required: false}

      - { label: "Price", name: "price", widget: "string" }
      - { label: "Point 1", name: "point1", widget: "string", required: false }
      - { label: "Point 2", name: "point2", widget: "string", required: false }
      - { label: "Point 3", name: "point3", widget: "string", required: false }
      - { label: "Point 4", name: "point4", widget: "string", required: false }
      - { label: "Point 5", name: "point5", widget: "string", required: false }


  - name: 3" Cinewhoop Build
    label: 3" Cinewhoop Build
    folder: modules/buildLists/3inch-cinewhoop/
    create: true
    slug: "{{order}}-{{day}}-{{month}}-{{year}}-{{Categcategoryory}}-{{title}}"
    sortable_fields: [order, title, category, color]
    view_groups: 
      - label: Category
        field: category
      - label: Price Range
        field: color
    view_filters: 
      - label: Frames
        field: category
        pattern: "Frames"
      - label: Motors
        field: category
        pattern: "Motors"
      - label: Flight Controllers
        field: category
        pattern: "Flight Controllers"
      - label: ESCs
        field: category
        pattern: "ESCs"
      - label: Video Transmitters
        field: category
        pattern: "Video Transmitters"
    fields:
      - label: Category
        name: category
        widget: "select"
        options:
          - { label: "Frames", value: "Frames" }
          - { label: "Motors", value: "Motors" }
          - { label: "Flight Controllers", value: "Flight Controllers" }
          - { label: "ESCs", value: "ESCs" }
          - { label: "AIOs", value: "AIOs" }
          - { label: "Video Transmitters", value: "Video Transmitters" }
      - label: Price Range
        name: color
        widget: "select"
        options:
          - { label: "Budget", value: "green" }
          - { label: "Mid-Range", value: "orange" }
          - { label: "High-end", value: "red" }
          - { label: "Varied", value: "violet" }
      - {label: "Visible", name: "visible", widget: "boolean", default: true}
      - { label: "Order", name: "order", widget: "number" }
      - { label: "Title", name: "title", widget: "text" }
      - { label: "Link", name: "link", widget: "text" }
      - { label: "Image", name: "img", widget: "image"}
      - { label: "Description", name: "text", widget: "text" }

      - { label: "Price", name: "price", widget: "text" }
      - { label: "Point 1", name: "point1", widget: "text", required: false }
      - { label: "Point 2", name: "point2", widget: "text", required: false }
      - { label: "Point 3", name: "point3", widget: "text", required: false }
      - { label: "Point 4", name: "point4", widget: "text", required: false }
      - { label: "Point 5", name: "point5", widget: "text", required: false }

  - name: 1s - 2s Micro Build
    label: 1s - 2s Micro Build
    folder: modules/buildLists/1s-2s-micro/
    create: true
    slug: "{{order}}-{{day}}-{{month}}-{{year}}-{{category}}-{{title}}"
    sortable_fields: [order, title, category, color]
    view_groups: 
      - label: Category
        field: category
      - label: Price Range
        field: color
    view_filters: 
      - label: Frames
        field: category
        pattern: "Frames"
      - label: Motors
        field: category
        pattern: "Motors"
      - label: AIOs
        field: category
        pattern: "AIOs"
      - label: Video Transmitters
        field: category
        pattern: "Video Transmitters"
    fields:
      - label: Category
        name: category
        widget: "select"
        options:
          - { label: "Frames", value: "Frames" }
          - { label: "Motors", value: "Motors" }
          - { label: "AIOs", value: "AIOs" }
          - { label: "Video Transmitters", value: "Video Transmitters" }
      - label: Price Range
        name: color
        widget: "select"
        options:
          - { label: "Budget", value: "green" }
          - { label: "Mid-Range", value: "orange" }
          - { label: "High-end", value: "red" }
          - { label: "Varied", value: "violet" }
      - {label: "Visible", name: "visible", widget: "boolean", default: true}
      - { label: "Order", name: "order", widget: "number" }
      - { label: "Title", name: "title", widget: "text" }
      - { label: "Link", name: "link", widget: "text" }
      - { label: "Image", name: "img", widget: "image"}
      - { label: "Description", name: "text", widget: "text" }

      - { label: "Price", name: "price", widget: "text" }
      - { label: "Point 1", name: "point1", widget: "text", required: false }
      - { label: "Point 2", name: "point2", widget: "text", required: false }
      - { label: "Point 3", name: "point3", widget: "text", required: false }
      - { label: "Point 4", name: "point4", widget: "text", required: false }
      - { label: "Point 5", name: "point5", widget: "text", required: false }

  - name: Equipment - Radio
    label: Equipment - Radio
    folder: modules/equipmentLists/radioList
    create: true
    slug: "{{order}}-{{day}}-{{month}}-{{year}}-{{category}}-{{title}}"
    sortable_fields: [order, title, category, color]
    view_groups: 
      - label: Category
        field: category
      - label: Price Range
        field: color
    view_filters: 
      - label: Radios
        field: category
        pattern: "Radios"
      - label: TX Modules
        field: category
        pattern: "TX Modules"
      - label: Receivers
        field: category
        pattern: "Receivers"
      - label: Antennas
        field: category
        pattern: "Antennas"
    fields:
      - label: Category
        name: category
        widget: "select"
        options:
          - { label: "Radios", value: "Radios" }
          - { label: "TX Modules", value: "TX Modules" }
          - { label: "Receivers", value: "Receivers" }
          - { label: "Antennas", value: "Antennas" }
      - { label: "Group", name: "group", widget: "text" }
      - label: Price Range
        name: color
        widget: "select"
        options:
          - { label: "Budget", value: "green" }
          - { label: "Mid-Range", value: "orange" }
          - { label: "High-end", value: "red" }
          - { label: "Varied", value: "violet" }
      - {label: "Visible", name: "visible", widget: "boolean", default: true}
      - { label: "Order", name: "order", widget: "number" }
      - { label: "Title", name: "title", widget: "text" }
      - { label: "Link", name: "link", widget: "text" }
      - { label: "Image", name: "img", widget: "image"}
      - { label: "Description", name: "text", widget: "markdown" }

      - { label: "Price", name: "price", widget: "text" }
      - { label: "Point 1", name: "point1", widget: "text", required: false }
      - { label: "Point 2", name: "point2", widget: "text", required: false }
      - { label: "Point 3", name: "point3", widget: "text", required: false }
      - { label: "Point 4", name: "point4", widget: "text", required: false }
      - { label: "Point 5", name: "point5", widget: "text", required: false }

  - name: Equipment - Video
    label: Equipment - Video
    folder: modules/equipmentLists/videoList
    create: true
    slug: "{{order}}-{{day}}-{{month}}-{{year}}-{{category}}-{{title}}"
    sortable_fields: [order, title, category, color]
    view_groups: 
      - label: Category
        field: category
      - label: Price Range
        field: color
    view_filters: 
      - label: Cameras
        field: category
        pattern: "Cameras"
      - label: Goggles
        field: category
        pattern: "Goggles"
      - label: Antennas
        field: category
        pattern: "Antennas"
      - label: Video Receivers
        field: category
        pattern: "Video Receivers"
    fields:
      - label: Category
        name: category
        widget: "select"
        options:
          - { label: "Cameras", value: "Cameras" }
          - { label: "Goggles", value: "Goggles" }
          - { label: "Antennas", value: "Antennas" }
          - { label: "Video Receivers", value: "Video Receivers" }
      - { label: "Group", name: "group", widget: "text" }
      - label: Price Range
        name: color
        widget: "select"
        options:
          - { label: "Budget", value: "green" }
          - { label: "Mid-Range", value: "orange" }
          - { label: "High-end", value: "red" }
          - { label: "Varied", value: "violet" }
      - {label: "Visible", name: "visible", widget: "boolean", default: true}
      - { label: "Order", name: "order", widget: "number" }
      - { label: "Title", name: "title", widget: "text" }
      - { label: "Link", name: "link", widget: "text" }
      - { label: "Image", name: "img", widget: "image"}
      - { label: "Description", name: "text", widget: "markdown" }

      - { label: "Price", name: "price", widget: "text" }
      - { label: "Point 1", name: "point1", widget: "text", required: false }
      - { label: "Point 2", name: "point2", widget: "text", required: false }
      - { label: "Point 3", name: "point3", widget: "text", required: false }
      - { label: "Point 4", name: "point4", widget: "text", required: false }
      - { label: "Point 5", name: "point5", widget: "text", required: false }

  - name: Articles
    label: Articles
    folder: modules/articles
    create: true
    slug: "{{category}}-{{title}}"
    sortable_fields: [order, title, category, color]
    view_groups:
      - label: Category
        field: category
    view_filters: 
      - label: Guides
        field: category
        pattern: "Guides"
      - label: Tutorials
        field: category
        pattern: "Tutorials"
      - label: News
        field: category
        pattern: "News"
      - label: Reviews
        field: category
        pattern: "Reviews"
      - label: Misc
        field: category
        pattern: "Misc"
    fields:
      - { label: "Title", name: "title", widget: "text" }
      - { label: "Description", name: "description", widget: "text" }
      - {label: "Visible", name: "visible", widget: "boolean", default: false}
      - label: Category
        name: category
        widget: "select"
        options:
          - { label: "Guides", value: "Guides" }
          - { label: "Tutorials", value: "Tutorials" }
          - { label: "News", value: "News" }
          - { label: "Reviews", value: "Reviews" }
          - { label: "Misc", value: "Misc" }
      - { label: "Author", name: "author", widget: "text" }
      - { label: "Image", name: "img", widget: "image" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Updated on", name: "updated", widget: "datetime" }
      - { label: "Content", name: "body", widget: "markdown" }

media_folder: "/static/uploads/"
public_folder: "/uploads/"

site_url: https://www.vitroidfpv.com/
display_url: https://www.vitroidfpv.com/
logo_url: https://www.vitroidfpv.com/favicon.png
